[package]
name = "actix-web-validator"
version = "0.1.0"
authors = ["Kolomatskiy Artem <a.kolomatskiy@rambler-co.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0"
derive_more = "0.99"
actix-http = "0.2.11"
validator = "0.10"
validator_derive = "0.10"
serde = "1.0.104"
serde_urlencoded = "0.6.1"
log = "0.4.8"
